[tool.ruff]
lint.ignore = ["E501"]

[tool.poetry]
name = "builder"
version = "0.3.1"
description = "GRAPEVNE Builder"
authors = ["Kraemer-lab"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
cachetools = "5.3.2"
certifi = "2023.7.22"
charset-normalizer = "3.1.0"
idna = "3.7"
iniconfig = "2.0.0"
packaging = "23.1"
pyyaml = "6.0.1"
requests = "2.32.2"
urllib3 = "2.0.7"


[tool.poetry.group.dev.dependencies]
ruff = "0.3.0"
pytest = "8.0.2"
coverage = "7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
